### PR TITLE
Main file added to conform to CommonJS and other datatables APIs

### PR DESCRIPTION
**Pull request by valerydev**

### CODE REVIEW

**Comment by DataTables** [comment]
I'm not sure I see the benefit of this to be honest. Its just an empty Javascript file that does nothing. Does CommonJS require a Javascript entry file?

**Comment by valerydev** [comment]
Without a main file in CommonJS you can't do what you said in the readme.md
`require('datatables.net-dt')(window, $)`
It just said module doesn't exists. There must exists a main file which exports the function that takes window and $

The style field you add to package.json is to be consume by browserify's transform "parcelify", browserify is for consuming CommonJS modules, unless you add deAMDfy transform.

By now, I have to add css file by hand :(

**Comment by DataTables** [comment]
Thanks! That's an error in the readme. It should just be `require('datatables.net')`

This repo only has style information in it since DataTables contains the Javascript defaults for DataTables styling.

**Comment by valerydev** [comment]
It's ok you `require('datatables.net')` but only if you have a main file, the issue here is that this module cannot be required and have its CSSs automatically exposed because it have no main file (Error: Cannot find module "datatables.net-dt").
Returning a function from this main file is just to keep consistency with other datatables.net APIs

**Comment by DataTables** [comment]
How does having a Javascript index file help with the CSS though?

This is something I've been really struggling with - there is no good way to include CSS as there is for Javascript. I've included a `style` parameter in package.json which appears to be the way other frameworks such as Bootstrap are going, but the package managers don't seem to be that interested in the CSS aspect which is frustrating.

**Comment by valerydev** [comment]
> How does having a Javascript index file help with the CSS though?

The main file have nothing related to CSS, the problem of not having a main file is more fundamental, it's because you must have one in order for your module to be consumable by a CommonJS loader. In other words your module can not even be required!

> This is something I've been really struggling with - there is no good way to include CSS as there is for Javascript...

[Browserify](http://browserify.org/) and [Webpack](http://webpack.github.io/docs/) have different ways to do this:
In Browserify the convention is using the [parcelify](https://github.com/rotundasoftware/parcelify) transform which consumes the "style" field from package.json, this field have a string with the path to the main CSS file (if there are more files you could @import them from this main CSS which is parsed recursively to find other css and other resources specified with url(...)) and it produces a css bundle with the contents of all combined.

In Webpack you use [css-loader](https://github.com/webpack/css-loader) (loaders in webpack are the same thing than tranforms in browserify) in combination with [style-loader](https://github.com/webpack/style-loader) so you can require a css file like this `require('./assets/css/main.css')` and this dynamicaly adds a link element in the DOM with the stylesheet. It also resolve recursively @import and url(...) in the css files as if they were requires, and in order to handle images and fonts you also need to configure [file-loader](https://github.com/webpack/file-loader) or [url-loader](https://github.com/webpack/url-loader).  

Not all modules containing styles can expose them using "style" field, e.g. [kendo-ui-core](https://www.npmjs.com/package/kendo-ui-core) have too many resources and you only want to load what you need, so in cases like this Webpack excels, using requires you only include the resources you need.

Note: I'm using webpack and in order to consume modules with the parcelify way to expose css (as this module does) I'm using [parcelify-loader](https://www.npmjs.com/package/parcelify-loader) either so I can load CSSs files both, by require or by style field in package.json

PD: IMHO Webpack is the perfect solution with requirable resources and code splitting you can handle cases like that of kendo-ui-core. If everybody upload the webpack way, handling css modularity would be easy, consistent, and intuitive

**Comment by DataTables** [comment]
Finally(!!!) done with f2093854f56a7e47958a41365f0e0f20e705b2da. I've updated all packages so this should work as expects across them all now (or at least with their next releases, which I'll do shortly).

**Pull request closed without merging**
